name: Hello World app CI

on:
  push:
    branches: ["develop"]

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
      - name: Build
        run: mvn -B package --file pom.xml
      - name: Copying jar
        run: mkdir artifact && cp target/github-actions-1.0.0.jar artifact
      - name: Uploading artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: artifact

  release: 
    needs: ['build']
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Downloading artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: artifact
      - name: Display structure of downloaded files
        run: ls -R
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Pushing image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: nbrovedan/github-actions:latest
          platforms: linux/amd64,linux/arm64